from .mock_media import car_image

CARS = [
    {
        "name": "Toyota Corolla",
        "category": "Economy",
        "location": "Downtown",
        "price_per_day": 38.00,
        "rating": 4.4,
        "image": car_image("#2563eb"),
        "tags": ["Bluetooth", "Backup Camera", "USB Charging"],
        "metadata": {"transmission": "Automatic", "seats": 5, "fuel_type": "Gas", "mpg": 34},
    },
    {
        "name": "Honda Civic",
        "category": "Economy",
        "location": "Downtown",
        "price_per_day": 40.00,
        "rating": 4.5,
        "image": car_image("#ef4444"),
        "tags": ["Bluetooth", "Apple CarPlay", "USB Charging"],
        "metadata": {"transmission": "Automatic", "seats": 5, "fuel_type": "Gas", "mpg": 33},
    },
    {
        "name": "Honda CR-V",
        "category": "SUV",
        "location": "Airport",
        "price_per_day": 62.00,
        "rating": 4.6,
        "image": car_image("#16a34a"),
        "tags": ["Bluetooth", "Backup Camera", "Apple CarPlay", "All-Wheel Drive"],
        "metadata": {"transmission": "Automatic", "seats": 5, "fuel_type": "Gas", "mpg": 28},
    },
    {
        "name": "Ford Explorer",
        "category": "SUV",
        "location": "Airport",
        "price_per_day": 74.00,
        "rating": 4.3,
        "image": car_image("#1f2937"),
        "tags": ["Backup Camera", "Third Row Seating", "Apple CarPlay"],
        "metadata": {"transmission": "Automatic", "seats": 7, "fuel_type": "Gas", "mpg": 24},
    },
    {
        "name": "Tesla Model 3",
        "category": "Electric",
        "location": "Downtown",
        "price_per_day": 89.00,
        "rating": 4.8,
        "image": car_image("#0ea5e9"),
        "tags": ["Autopilot", "Bluetooth", "Backup Camera", "Fast Charging"],
        "metadata": {"transmission": "Automatic", "seats": 5, "fuel_type": "Electric", "mpg": "132 MPGe"},
    },
    {
        "name": "Chevrolet Bolt EUV",
        "category": "Electric",
        "location": "Airport",
        "price_per_day": 71.00,
        "rating": 4.4,
        "image": car_image("#f59e0b"),
        "tags": ["Bluetooth", "Backup Camera", "Fast Charging"],
        "metadata": {"transmission": "Automatic", "seats": 5, "fuel_type": "Electric", "mpg": "115 MPGe"},
    },
    {
        "name": "BMW 5 Series",
        "category": "Luxury",
        "location": "Downtown",
        "price_per_day": 118.00,
        "rating": 4.7,
        "image": car_image("#111827"),
        "tags": ["Leather Seats", "Apple CarPlay", "Backup Camera", "Heated Seats"],
        "metadata": {"transmission": "Automatic", "seats": 5, "fuel_type": "Gas", "mpg": 27},
    },
    {
        "name": "Mercedes-Benz E-Class",
        "category": "Luxury",
        "location": "Airport",
        "price_per_day": 125.00,
        "rating": 4.8,
        "image": car_image("#f8fafc"),
        "tags": ["Leather Seats", "Bluetooth", "Heated Seats", "Sunroof"],
        "metadata": {"transmission": "Automatic", "seats": 5, "fuel_type": "Gas", "mpg": 26},
    },
    {
        "name": "Jeep Wrangler",
        "category": "SUV",
        "location": "Downtown",
        "price_per_day": 68.00,
        "rating": 4.2,
        "image": car_image("#65a30d"),
        "tags": ["4x4", "Removable Top", "Bluetooth"],
        "metadata": {"transmission": "Manual", "seats": 4, "fuel_type": "Gas", "mpg": 22},
    },
]
